"""SL-1 replay-equivalence + idempotence tests.

This is the crux of SL-1: prove that replaying a non-trivial committed event log
reproduces the canonical state, and that replay is deterministic.

Three committed artifacts under ``tests/fixtures/replay/sample-project/`` drive
these tests:

* ``events.jsonl``       — a realistic, deterministic audit log (project init,
                            multiple tasks, a claim with lease + heartbeat/renew,
                            a review acceptance, a stale-claim reap, a sync
                            mapping). Every line is a canonical event — no
                            tombstones (SL1-RR-1 guarantee).
* ``audit.jsonl``        — the sibling audit trail (rejections + idempotent
                            no-ops). Never replayed; present to prove the
                            scenario exercised both failure modes.
* ``expected-state.json`` — the golden ``serialize_state`` snapshot for that log.

Both artifacts are regenerated by a deliberate, documented human step — see
``tests/fixtures/replay/regenerate.py``. The tests NEVER regenerate them; a drift
between the committed golden and a freshly built/replayed snapshot is a real
failure to surface, not something to paper over.

Properties proven
------------------
1. **Equivalence** — building state the NORMAL way (append EventDrafts derived
   from the committed events) and the REPLAY way (replay_from_empty over the
   same events file) yields ``serialize_state`` outputs that are equal to each
   other AND equal to the committed golden snapshot.
2. **Idempotence** — replaying the same events into two independent scratch
   databases yields byte-identical snapshots.
3. **Poison-line impossibility** — the committed events.jsonl contains ZERO
   tombstone lines; every line is a real event that replay applies without a
   skip-list.

All scratch databases live under ``tmp_path`` and are never written into the
repo. No ``.db`` file is tracked.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from fakoli_state.clock import FrozenClock
from fakoli_state.state.models import EventDraft
from fakoli_state.state.snapshot import serialize_state
from fakoli_state.state.sqlite import SqliteBackend

# Suite-wide frozen anchor (matches the generator and conftest).
_T0 = datetime(2026, 5, 24, 18, 0, 0, tzinfo=UTC)

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "replay" / "sample-project"
_EVENTS_PATH = _FIXTURE_DIR / "events.jsonl"
_AUDIT_PATH = _FIXTURE_DIR / "audit.jsonl"
_GOLDEN_PATH = _FIXTURE_DIR / "expected-state.json"


# ---------------------------------------------------------------------------
# Fixture loading helpers
# ---------------------------------------------------------------------------


def _load_committed_events() -> list[dict[str, Any]]:
    """Return the committed events.jsonl as a list of raw dicts."""
    with _EVENTS_PATH.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _load_golden() -> dict[str, Any]:
    """Return the committed golden snapshot dict."""
    with _GOLDEN_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def _make_backend(state_dir: Path, *, db_name: str = "state.db") -> SqliteBackend:
    """A fresh, initialized SqliteBackend rooted under ``state_dir``.

    Uses a FrozenClock so any clock read during append/replay is deterministic.
    Both paths are fully deterministic.
    """
    db_path = str(state_dir / db_name)
    events_path = str(state_dir / "events.jsonl")
    Path(events_path).touch()
    b = SqliteBackend(db_path=db_path, events_path=events_path, clock=FrozenClock(_T0))
    b.initialize()
    return b


def _build_normal(state_dir: Path) -> SqliteBackend:
    """Build state the NORMAL way: append an EventDraft for each committed event.

    Each committed event is converted to an EventDraft (id stripped — the
    backend assigns sequential ids from its log-authority counter). Because the
    event sequence is identical, the backend assigns the same canonical ids
    E000001..E000024 and produces byte-equivalent state to replay_from_empty.

    This exercises the production write path (append) and proves it produces
    the same state as the replay path for the same event sequence.
    """
    b = _make_backend(state_dir)
    for raw in _load_committed_events():
        # Strip the id: EventDraft has no id field (the backend assigns it).
        draft_data = {k: v for k, v in raw.items() if k != "id"}
        draft = EventDraft.model_validate(draft_data)
        b.append(draft)
    return b


def _serialize(backend: SqliteBackend) -> dict[str, Any]:
    return serialize_state(backend)


def _canonical_json(snap: dict[str, Any]) -> str:
    return json.dumps(snap, sort_keys=True)


# ---------------------------------------------------------------------------
# Equivalence
# ---------------------------------------------------------------------------


def test_normal_and_replay_match_each_other_and_the_golden(tmp_path: Path) -> None:
    """serialize_state(normal) == serialize_state(replay) == committed golden.

    The 'normal' backend appends EventDrafts derived from the committed events;
    the 'replay' backend rebuilds via replay_from_empty over the same events
    file. All three snapshots must be byte-identical.
    """
    normal_dir = tmp_path / "normal"
    replay_dir = tmp_path / "replay"
    normal_dir.mkdir()
    replay_dir.mkdir()

    normal = _build_normal(normal_dir)
    replay = _make_backend(replay_dir)
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))

        normal_snap = _serialize(normal)
        replay_snap = _serialize(replay)
        golden = _load_golden()

        # Vacuity guard: ensure the golden is non-degenerate before comparing.
        # If the golden were empty/blank, the three-way equality below would pass
        # vacuously even though replay is completely broken.
        assert golden["project"] is not None and len(golden["tasks"]) == 3, (
            "golden is degenerate (project is None or task count != 3) — "
            "regenerate the fixture via tests/fixtures/replay/regenerate.py"
        )

        normal_json = _canonical_json(normal_snap)
        replay_json = _canonical_json(replay_snap)
        golden_json = _canonical_json(golden)

        assert normal_json == replay_json, (
            "normal-path and replay-path snapshots diverge — replay does NOT "
            "reproduce canonical state. Diff the two serialize_state outputs to "
            "find the divergent collection."
        )
        assert replay_json == golden_json, (
            "replayed snapshot does not match the committed golden "
            "(expected-state.json). Either replay regressed, or the golden is "
            "stale — if the scenario legitimately changed, regenerate via "
            "tests/fixtures/replay/regenerate.py and commit the new artifacts."
        )
    finally:
        normal.close()
        replay.close()


def test_replayed_state_is_well_formed(tmp_path: Path) -> None:
    """Sanity: the replayed snapshot has the full canonical shape and content.

    Guards against a 'golden == replay' match that is vacuously true because
    both are empty/degenerate. Asserts the scenario's headline rows are present.
    """
    replay = _make_backend(tmp_path)
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))
        snap = _serialize(replay)

        assert set(snap.keys()) == {
            "project", "prd", "features", "tasks",
            "claims", "reviews", "evidence", "requirements", "sync_mappings",
        }, (
            f"serialize_state returned unexpected keys {set(snap.keys())}. "
            "A likely cause is a new collection added to serialize_state — update "
            "the expected key set here AND regenerate the fixture."
        )
        assert snap["project"] is not None
        assert snap["prd"] is not None

        # Three tasks were created.
        assert {t["id"] for t in snap["tasks"]} == {"T001", "T002", "T003"}

        # Two claims, both terminal (released + stale) — proves list_claims (ALL).
        claims_by_id = {c["id"]: c["status"] for c in snap["claims"]}
        assert claims_by_id == {"C001": "released", "C002": "stale"}

        # Exactly one evidence row — the duplicate EV-DUP was a no-op (audit only).
        assert [e["id"] for e in snap["evidence"]] == ["EV001"]

        # The task.applied acceptance produced one review row.
        assert len(snap["reviews"]) == 1

        # The sync mapping survived replay.
        assert [(m["task_id"], m["external_system"]) for m in snap["sync_mappings"]] == [
            ("T001", "github_issues"),
        ]
    finally:
        replay.close()


def test_events_jsonl_contains_no_tombstone_lines() -> None:
    """The committed events.jsonl contains ZERO tombstone/audit lines.

    SL1-RR-1 guarantee: every line in events.jsonl is a real canonical event.
    Tombstones (rejections, idempotent no-ops) live in audit.jsonl only.
    replay_from_empty applies every line with no skip-list — poison lines are
    structurally impossible.
    """
    events = _load_committed_events()
    tombstone_actions = ("error.transaction_aborted", "warn.idempotent_no_op")
    for raw in events:
        action = raw.get("action", "")
        assert action not in tombstone_actions, (
            f"events.jsonl contains a tombstone line with action={action!r}. "
            "SL1-RR-1 requires all tombstones to live in audit.jsonl. "
            "Regenerate the fixture via tests/fixtures/replay/regenerate.py."
        )
    # Also verify all lines have the canonical E######-format id.
    for raw in events:
        eid = raw.get("id", "")
        assert eid.startswith("E") and eid[1:].isdigit(), (
            f"events.jsonl line has non-canonical id={eid!r}. "
            "Every line in events.jsonl must be a real event with a monotonic id."
        )


def test_audit_jsonl_contains_rejection_and_idempotent_no_op() -> None:
    """The committed audit.jsonl contains one rejection and one idempotent_no_op.

    These entries exist specifically to prove the scenario exercised both failure
    modes and that they landed in audit.jsonl, not events.jsonl.
    """
    with _AUDIT_PATH.open(encoding="utf-8") as fh:
        audit_lines = [json.loads(line) for line in fh if line.strip()]

    kinds = [entry.get("kind") for entry in audit_lines]
    assert "rejection" in kinds, (
        "audit.jsonl is missing a 'rejection' entry — the EventRejected path was "
        "not exercised. Regenerate the fixture."
    )
    assert "idempotent_no_op" in kinds, (
        "audit.jsonl is missing an 'idempotent_no_op' entry — the IdempotentNoOp "
        "path was not exercised. Regenerate the fixture."
    )
    # Audit entries must NOT have an 'id' field — they are not events.
    for entry in audit_lines:
        assert "id" not in entry, (
            f"audit.jsonl entry has an 'id' field: {entry!r}. "
            "Audit entries are not events and must not carry E###### ids."
        )


# ---------------------------------------------------------------------------
# Idempotence
# ---------------------------------------------------------------------------


def test_replay_is_idempotent_across_independent_dbs(tmp_path: Path) -> None:
    """Replaying the same events into two independent scratch dbs is byte-stable."""
    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()

    backend_a = _make_backend(dir_a)
    backend_b = _make_backend(dir_b)
    try:
        backend_a.replay_from_empty(str(_EVENTS_PATH))
        backend_b.replay_from_empty(str(_EVENTS_PATH))

        json_a = _canonical_json(_serialize(backend_a))
        json_b = _canonical_json(_serialize(backend_b))

        assert json_a == json_b, (
            "two independent replays of the same events produced different "
            "snapshots — replay is non-deterministic. This is a real replay bug."
        )
    finally:
        backend_a.close()
        backend_b.close()


def test_repeated_replay_into_same_backend_is_stable(tmp_path: Path) -> None:
    """Replaying twice into the SAME backend (delete+rebuild) is byte-stable.

    replay_from_empty deletes and recreates its own db on every call, so a
    second replay must reproduce the first replay's snapshot exactly.
    """
    backend = _make_backend(tmp_path)
    try:
        backend.replay_from_empty(str(_EVENTS_PATH))
        first = _canonical_json(_serialize(backend))

        backend.replay_from_empty(str(_EVENTS_PATH))
        second = _canonical_json(_serialize(backend))

        assert first == second
    finally:
        backend.close()


def test_no_tracked_db_artifacts_under_fixture_dir() -> None:
    """The committed fixture dir contains only the three text artifacts — no .db.

    Scratch databases must live under tmp_path; none may leak into the repo.
    The three expected artifacts are: events.jsonl, audit.jsonl,
    expected-state.json.
    """
    tracked = sorted(p.name for p in _FIXTURE_DIR.iterdir() if p.is_file())
    assert tracked == ["audit.jsonl", "events.jsonl", "expected-state.json"], (
        f"unexpected file(s) committed under the replay fixture dir: {tracked}. "
        "Scratch databases must live under tmp_path, never in the repo. "
        "Expected: audit.jsonl, events.jsonl, expected-state.json."
    )
    assert not any(p.suffix == ".db" for p in _FIXTURE_DIR.iterdir())
